repos:
- repo: git://github.com/nclouds/pre-commit-terraform
  rev: v1.37.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_tfsec
    - id: terraform_docs
      files: (\.tf|\.tfvars)$
